
services:
  tg_bot:
    env_file:
      - .env
    build:
      context: ./tg_bot
      dockerfile: Dockerfile
    depends_on:
      pg_container:
        condition: service_healthy
      redis_container:
        condition: service_healthy
    volumes:
      - ./tg_bot/src:/app

  pg_container:
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_DATABASE_NAME}
      POSTGRES_PASSWORD: ${PG_USER_PASSWORD}
      POSTGRES_USER: ${PG_USER_NAME}
    build:
      context: ./docker_confs/postgres
      dockerfile: Dockerfile
    volumes:
      - ./docker_confs/postgres/data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER_NAME} -d ${PG_DATABASE_NAME}"]
      interval: 10s
      retries: 5
      timeout: 10s
  
  redis_container:
    build:
      context: ./docker_confs/redis
      dockerfile: Dockerfile
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  # celery_container:
  #   build:
  #     context: ./docker_confs/celery
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   # volumes:
  #   #   - ./tg_bot/src/settings:/app/settings
  #   #   - ./tg_bot/src/utils/api_integrations/sound_cloud_api:/app/celery/extra_funcs/sc_funcs
  #   depends_on:
  #     redis_container:
  #       condition: service_healthy